source 'http://rubygems.org'

gem 'chef'
gem 'chefspec'
gem 'test-kitchen'
gem 'kitchen-vagrant'
gem 'kitchen-inspec'
gem 'foodcritic'
gem 'rubocop'
gem 'rainbow'
gem 'berkshelf'
gem 'fauxhai'

gem 'netaddr'
gem 'net_http_unix'
gem 'inifile'
gem 'rbeapi'
